In [56]:
import numpy as np 

In [57]:
import pandas as pd

In [58]:
short_pos = open("pos.txt","r").read()
short_neg = open("neg.txt","r").read()

In [59]:
documents = []
documents1 = []
documents2 = []


for r in short_pos.split('\n'):
    documents1.append( r )
    documents.append( r )

for r in short_neg.split('\n'):
    documents2.append( r )
    documents.append( r )

In [60]:
documents[5]

'the film provides some great insight into the neurotic mindset of all comics -- even those who have reached the absolute top of the game . '

In [61]:
documents1[5]

'the film provides some great insight into the neurotic mindset of all comics -- even those who have reached the absolute top of the game . '

In [62]:
documents2[5]

"the story is also as unoriginal as they come , already having been recycled more times than i'd care to count . "

In [63]:
from sklearn.feature_extraction.text import CountVectorizer

In [64]:
vector = CountVectorizer()

In [65]:
vector.fit(documents)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [66]:
vector.vocabulary_

{'the': 16295,
 'rock': 13661,
 'is': 8685,
 'destined': 4314,
 'to': 16508,
 'be': 1450,
 '21st': 99,
 'century': 2560,
 'new': 10848,
 'conan': 3234,
 'and': 750,
 'that': 16293,
 'he': 7480,
 'going': 6989,
 'make': 9806,
 'splash': 15204,
 'even': 5613,
 'greater': 7135,
 'than': 16286,
 'arnold': 985,
 'schwarzenegger': 14067,
 'jean': 8786,
 'claud': 2870,
 'van': 17457,
 'damme': 3894,
 'or': 11236,
 'steven': 15448,
 'segal': 14217,
 'gorgeously': 7030,
 'elaborate': 5155,
 'continuation': 3429,
 'of': 11113,
 'lord': 9620,
 'rings': 13606,
 'trilogy': 16772,
 'so': 14940,
 'huge': 7874,
 'column': 3073,
 'words': 18151,
 'cannot': 2372,
 'adequately': 379,
 'describe': 4271,
 'co': 2986,
 'writer': 18220,
 'director': 4478,
 'peter': 11841,
 'jackson': 8735,
 'expanded': 5744,
 'vision': 17646,
 'tolkien': 16530,
 'middle': 10220,
 'earth': 5052,
 'effective': 5119,
 'but': 2250,
 'too': 16556,
 'tepid': 16242,
 'biopic': 1680,
 'if': 8005,
 'you': 18293,
 'sometimes': 15022,


In [67]:
vector.get_feature_names()

['00',
 '000',
 '007',
 '10',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '10th',
 '11',
 '110',
 '112',
 '117',
 '11th',
 '12',
 '120',
 '123',
 '125',
 '127',
 '129',
 '12th',
 '13',
 '133',
 '13th',
 '14',
 '140',
 '146',
 '15',
 '15th',
 '16',
 '163',
 '168',
 '17',
 '170',
 '179',
 '1790',
 '18',
 '180',
 '1873',
 '1899',
 '18th',
 '19',
 '1915',
 '1920',
 '1930s',
 '1933',
 '1934',
 '1937',
 '1938',
 '1940s',
 '1949',
 '1950',
 '1950s',
 '1952',
 '1953',
 '1954',
 '1955',
 '1957',
 '1958',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1967',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1975',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1982',
 '1983',
 '1984',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1997',
 '1998',
 '1999',
 '19th',
 '20',
 '2000',
 '2001',
 '2002',
 '20th',
 '21',
 '21st',
 '22',
 '24',
 '2455',
 '25',
 '2525',
 '25s',
 '26',
 '270',
 '28k',
 '295',
 '30',
 '300',
 '3000',
 '30s',
 '33',
 '37',
 '3d',
 '40',
 '400'

In [68]:
counts1 = vector.transform(documents1)

In [69]:
counts1.shape

(5331, 18361)

In [70]:
array1 = counts1.toarray()

In [71]:
array1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [72]:
DataFrame1 = np.array(array1)

In [73]:
DataFrame1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [74]:
DataFrame1[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [75]:
myDataFrame1 = pd.DataFrame(DataFrame1)

In [76]:
myDataFrame1

0      1      2      3      4      5      6      7      8      9      \
0         0      0      0      0      0      0      0      0      0      0   
1         0      0      0      0      0      0      0      0      0      0   
2         0      0      0      0      0      0      0      0      0      0   
3         0      0      0      0      0      0      0      0      0      0   
4         0      0      0      0      0      0      0      0      0      0   
5         0      0      0      0      0      0      0      0      0      0   
6         0      0      0      0      0      0      0      0      0      0   
7         0      0      0      0      0      0      0      0      0      0   
8         0      0      0      0      0      0      0      0      0      0   
9         0      0      0      0      0      0      0      0      0      0   
10        0      0      0      0      0      0      0      0      0      0   
11        0      0      0      0      0      0      0      0      0      0   
12        0      0      0      0      0      0      0      0      0      0   
13        0      0      0      0      0      0      0      0      0      0   
14        0      0      0      0      0      0      0      0      0      0   
15        0      0      0      0      0      0      0      0      0      0   
16        0      0      0      0      0      0      0      0      0      0   
17        0      0      0      0      0      0      0      0      0      0   
18        0      0      0      0      0      0      0      0      0      0   
19        0      0      0      0      0      0      0      0      0      0   
20        0      0      0      0      0      0      0      0      0      0   
21        0      0      0      0      0      0      0      0      0      0   
22        0      0      0      0      0      0      0      0      0      0   
23        0      0      0      0      0      0      0      0      0      0   
24        0      0      0      0      0      0      0      0      0      0   
25        0      0      0      0      0      0      0      0      0      0   
26        0      0      0      0      0      0      0      0      0      0   
27        0      0      0      0      0      0      0      0      0      0   
28        0      0      0      0      0      0      0      0      0      0   
29        0      0      0      0      0      0      0      0      0      0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5301      0      0      0      0      0      0      0      0      0      0   
5302      0      0      0      0      0      0      0      0      0      0   
5303      0      0      0      0      0      0      0      0      0      0   
5304      0      0      0      0      0      0      0      0      0      0   
5305      0      0      0      0      0      0      0      0      0      0   
5306      0      0      0      0      0      0      0      0      0      0   
5307      0      0      0      0      0      0      0      0      0      0   
5308      0      0      0      0      0      0      0      0      0      0   
5309      0      0      0      0      0      0      0      0      0      0   
5310      0      0      0      0      0      0      0      0      0      0   
5311      0      0      0      0      0      0      0      0      0      0   
5312      0      0      0      0      0      0      0      0      0      0   
5313      0      0      0      0      0      0      0      0      0      0   
5314      0      0      0      0      0      0      0      0      0      0   
5315      0      0      0      0      0      0      0      0      0      0   
5316      0      0      0      0      0      0      0      0      0      0   
5317      0      0      0      0      0      0      0      0      0      0   
5318      0      0      0      0      0      0      0      0      0      0   
5319      0      0      0      0      0      0      0      0      0      0   
5320      0      0      0   

In [77]:
myDataFrame1['class'] = 'pos'

In [78]:
myDataFrame1

0  1  2  3  4  5  6  7  8  9  ...    18352  18353  18354  18355  18356  \
0     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
1     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
2     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
3     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
4     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
6     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
7     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
8     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
9     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
11    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
12    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
13    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
14    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
15    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
16    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
17    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
18    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
19    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
20    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
21    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
22    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
23    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
24    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
25    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
26    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
27    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
28    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
29    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
...  .. .. .. .. .. .. .. .. .. ..  ...      ...    ...    ...    ...    ...   
5301  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5302  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5303  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5304  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5305  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5306  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5307  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5308  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5309  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5310  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5311  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5312  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5313  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5314  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5315  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5316  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5317  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5318  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5319  

In [79]:
counts2 = vector.transform(documents2)

In [80]:
counts2.shape

(5331, 18361)

In [81]:
array2 = counts2.toarray()

In [82]:
DataFrame2 = np.array(array2)

In [83]:
DataFrame2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [84]:
myDataFrame2 = pd.DataFrame(DataFrame2)

In [85]:
myDataFrame2['class'] = 'neg'

In [86]:
myDataFrame2

0  1  2  3  4  5  6  7  8  9  ...    18352  18353  18354  18355  18356  \
0     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
1     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
2     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
3     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
4     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
6     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
7     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
8     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
9     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
11    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
12    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
13    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
14    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
15    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
16    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
17    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
18    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
19    0  0  0  0  1  0  0  0  0  0  ...        0      0      0      0      0   
20    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
21    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
22    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
23    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
24    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
25    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
26    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
27    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
28    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
29    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
...  .. .. .. .. .. .. .. .. .. ..  ...      ...    ...    ...    ...    ...   
5301  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5302  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5303  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5304  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5305  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5306  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5307  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5308  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5309  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5310  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5311  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5312  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5313  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5314  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5315  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5316  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5317  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5318  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5319  

In [87]:
frames = [myDataFrame1, myDataFrame2]

In [88]:
df = pd.concat(frames)

In [89]:
df

0  1  2  3  4  5  6  7  8  9  ...    18352  18353  18354  18355  18356  \
0     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
1     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
2     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
3     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
4     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
6     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
7     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
8     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
9     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
11    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
12    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
13    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
14    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
15    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
16    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
17    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
18    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
19    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
20    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
21    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
22    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
23    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
24    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
25    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
26    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
27    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
28    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
29    0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
...  .. .. .. .. .. .. .. .. .. ..  ...      ...    ...    ...    ...    ...   
5301  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5302  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5303  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5304  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5305  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5306  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5307  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5308  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5309  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5310  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5311  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5312  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5313  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5314  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5315  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5316  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5317  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5318  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5319  

In [90]:
df = df.sample(frac=1).reset_index(drop=True)

In [91]:
df

0  1  2  3  4  5  6  7  8  9  ...    18352  18353  18354  18355  18356  \
0      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
1      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
2      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
3      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
4      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
5      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
6      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
7      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
8      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
9      0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
11     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
12     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
13     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
14     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
15     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
16     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
17     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
18     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
19     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
20     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
21     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
22     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
23     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
24     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
25     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
26     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
27     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
28     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
29     0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
...   .. .. .. .. .. .. .. .. .. ..  ...      ...    ...    ...    ...    ...   
10632  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10633  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10634  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10635  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10636  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10637  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10638  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10639  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10640  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10641  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10642  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10643  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10644  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10645  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10646  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10647  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10648  0  0  0  0  0  0  0  0  0  0  ...        0      0      0      0      0   
10649  0  0  0  0  0  0  0  0  0  0  .

In [92]:
df[df[5] == 1]

0  1  2  3  4  5  6  7  8  9  ...    18352  18353  18354  18355  18356  \
2724  0  0  0  0  0  1  0  0  0  0  ...        0      0      0      0      0   
3256  0  0  0  0  0  1  0  0  0  0  ...        0      0      0      0      0   
3739  0  0  0  0  0  1  0  0  0  0  ...        0      0      0      0      0   
4189  0  0  0  0  0  1  0  0  0  0  ...        0      0      0      0      0   
5383  0  0  0  0  0  1  0  0  0  0  ...        0      0      0      0      0   
5530  0  0  0  0  0  1  0  0  0  0  ...        0      0      0      0      0   
8105  0  0  0  0  0  1  0  0  0  0  ...        0      0      0      0      0   

      18357  18358  18359  18360  class  
2724      0      0      0      0    pos  
3256      0      0      0      0    pos  
3739      0      0      0      0    neg  
4189      0      0      0      0    pos  
5383      0      0      0      0    neg  
5530      0      0      0      0    pos  
8105      0      0      0      0    neg  

[7 rows x 18362 columns]

In [93]:
#split data into 2 matrix - X and y
X = df.iloc[:, :18361]
y = df.iloc[:,-1]

In [94]:
X

0      1      2      3      4      5      6      7      8      9      \
0          0      0      0      0      0      0      0      0      0      0   
1          0      0      0      0      0      0      0      0      0      0   
2          0      0      0      0      0      0      0      0      0      0   
3          0      0      0      0      0      0      0      0      0      0   
4          0      0      0      0      0      0      0      0      0      0   
5          0      0      0      0      0      0      0      0      0      0   
6          0      0      0      0      0      0      0      0      0      0   
7          0      0      0      0      0      0      0      0      0      0   
8          0      0      0      0      0      0      0      0      0      0   
9          0      0      0      0      0      0      0      0      0      0   
10         0      0      0      0      0      0      0      0      0      0   
11         0      0      0      0      0      0      0      0      0      0   
12         0      0      0      0      0      0      0      0      0      0   
13         0      0      0      0      0      0      0      0      0      0   
14         0      0      0      0      0      0      0      0      0      0   
15         0      0      0      0      0      0      0      0      0      0   
16         0      0      0      0      0      0      0      0      0      0   
17         0      0      0      0      0      0      0      0      0      0   
18         0      0      0      0      0      0      0      0      0      0   
19         0      0      0      0      0      0      0      0      0      0   
20         0      0      0      0      0      0      0      0      0      0   
21         0      0      0      0      0      0      0      0      0      0   
22         0      0      0      0      0      0      0      0      0      0   
23         0      0      0      0      0      0      0      0      0      0   
24         0      0      0      0      0      0      0      0      0      0   
25         0      0      0      0      0      0      0      0      0      0   
26         0      0      0      0      0      0      0      0      0      0   
27         0      0      0      0      0      0      0      0      0      0   
28         0      0      0      0      0      0      0      0      0      0   
29         0      0      0      0      0      0      0      0      0      0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
10632      0      0      0      0      0      0      0      0      0      0   
10633      0      0      0      0      0      0      0      0      0      0   
10634      0      0      0      0      0      0      0      0      0      0   
10635      0      0      0      0      0      0      0      0      0      0   
10636      0      0      0      0      0      0      0      0      0      0   
10637      0      0      0      0      0      0      0      0      0      0   
10638      0      0      0      0      0      0      0      0      0      0   
10639      0      0      0      0      0      0      0      0      0      0   
10640      0      0      0      0      0      0      0      0      0      0   
10641      0      0      0      0      0      0      0      0      0      0   
10642      0      0      0      0      0      0      0      0      0      0   
10643      0      0      0      0      0      0      0      0      0      0   
10644      0      0      0      0      0      0      0      0      0      0   
10645      0      0      0      0      0      0      0      0      0      0   
10646      0      0      0      0      0      0      0      0      0      0   
10647      0      0      0      0      0      0      0      0      0      0   
10648      0      0      0      0      0      0      0      0      0      0   
10649      0      0      0      0      0      0      0      0      0      0   
10650      0      0      0      0      0      0      0   

In [95]:
y

0        pos
1        neg
2        pos
3        pos
4        neg
5        pos
6        pos
7        neg
8        pos
9        pos
10       neg
11       neg
12       neg
13       neg
14       pos
15       pos
16       pos
17       neg
18       pos
19       neg
20       pos
21       pos
22       neg
23       pos
24       neg
25       pos
26       neg
27       pos
28       pos
29       pos
        ... 
10632    pos
10633    pos
10634    pos
10635    neg
10636    neg
10637    pos
10638    pos
10639    neg
10640    neg
10641    pos
10642    neg
10643    neg
10644    neg
10645    pos
10646    neg
10647    neg
10648    pos
10649    neg
10650    pos
10651    neg
10652    pos
10653    pos
10654    pos
10655    neg
10656    neg
10657    pos
10658    neg
10659    pos
10660    neg
10661    pos
Name: class, Length: 10662, dtype: object

In [96]:
X = df.iloc[:, :18361].values
y = df.iloc[:,-1].values

In [97]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [98]:
y

array(['pos', 'neg', 'pos', ..., 'pos', 'neg', 'pos'], dtype=object)

In [99]:
#splitting of data into train and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [100]:
y_test

array(['pos', 'pos', 'neg', ..., 'neg', 'neg', 'pos'], dtype=object)

In [101]:
# #feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [102]:
X_train

array([[-0.01157637,  0.        , -0.01637256, ...,  0.        ,
        -0.01157637, -0.01157637],
       [-0.01157637,  0.        , -0.01637256, ...,  0.        ,
        -0.01157637, -0.01157637],
       [-0.01157637,  0.        , -0.01637256, ...,  0.        ,
        -0.01157637, -0.01157637],
       ...,
       [-0.01157637,  0.        , -0.01637256, ...,  0.        ,
        -0.01157637, -0.01157637],
       [-0.01157637,  0.        , -0.01637256, ...,  0.        ,
        -0.01157637, -0.01157637],
       [-0.01157637,  0.        , -0.01637256, ...,  0.        ,
        -0.01157637, -0.01157637]])

In [103]:
#fit your training data to NB
from sklearn.naive_bayes import GaussianNB

In [104]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [105]:
#predict
y_predictor = classifier.predict(X_test)

In [106]:
y_predictor

array(['pos', 'pos', 'pos', ..., 'pos', 'neg', 'pos'], dtype='<U3')

In [107]:
#detect things using confusion matrix
from sklearn.metrics import confusion_matrix
falseCaci = confusion_matrix(y_test, y_predictor)

In [108]:
falseCaci

array([[ 848,  769],
       [ 381, 1201]], dtype=int64)

In [109]:
 from sklearn.metrics import accuracy_score

In [110]:
accuracy_score(y_test, y_predictor, normalize=True, sample_weight=None)

0.6405126602063145